<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Core.csproj" />
    <ProjectReference Include="..\Property.Application\Property.Application.csproj" />
    <ProjectReference Include="..\Property.Data\Property.Data.csproj" />
    <ProjectReference Include="..\..\Organization\Organization.Shared\Organization.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
